// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRealWorld.DAL;

#nullable disable

namespace MyRealWorld.Migrations
{
    [DbContext(typeof(MRWContext))]
    [Migration("20250528180931_ChangedNames_projects_pictures3")]
    partial class ChangedNames_projects_pictures3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyRealWorld.DAL.KeyWords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KWS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KeyWords");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Project_Pictures", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("PictureID")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "PictureID");

                    b.HasIndex("PictureID");

                    b.ToTable("Project_Pictures");
                });

            modelBuilder.Entity("MyRealWorld.DAL.ProjectsKW", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<int?>("KeyWordsId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "KWId");

                    b.HasIndex("KeyWordsId");

                    b.ToTable("ProjectsKW");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Project_Pictures", b =>
                {
                    b.HasOne("MyRealWorld.DAL.Picture", "pictures")
                        .WithMany("projpics")
                        .HasForeignKey("PictureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyRealWorld.DAL.Project", null)
                        .WithMany("projpics")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pictures");
                });

            modelBuilder.Entity("MyRealWorld.DAL.ProjectsKW", b =>
                {
                    b.HasOne("MyRealWorld.DAL.KeyWords", null)
                        .WithMany("projkw")
                        .HasForeignKey("KeyWordsId");

                    b.HasOne("MyRealWorld.DAL.Project", null)
                        .WithMany("projkw")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyRealWorld.DAL.KeyWords", b =>
                {
                    b.Navigation("projkw");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Picture", b =>
                {
                    b.Navigation("projpics");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Project", b =>
                {
                    b.Navigation("projkw");

                    b.Navigation("projpics");
                });
#pragma warning restore 612, 618
        }
    }
}
