// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRealWorld.DAL;

#nullable disable

namespace MyRealWorld.Migrations
{
    [DbContext(typeof(MRWContext))]
    [Migration("20250528171925_UpdateFK_projects")]
    partial class UpdateFK_projects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyRealWorld.DAL.KeyWords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KWS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KeyWords");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Project_Pictures", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("PictureID")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "PictureID");

                    b.HasIndex("ProjectsId");

                    b.ToTable("Project_Pictures");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MyRealWorld.DAL.ProjectsKW", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<int?>("KeyWordsId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "KWId");

                    b.HasIndex("KeyWordsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("ProjectsKW");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Project_Pictures", b =>
                {
                    b.HasOne("MyRealWorld.DAL.Projects", null)
                        .WithMany("projpics")
                        .HasForeignKey("ProjectsId");
                });

            modelBuilder.Entity("MyRealWorld.DAL.ProjectsKW", b =>
                {
                    b.HasOne("MyRealWorld.DAL.KeyWords", null)
                        .WithMany("projkw")
                        .HasForeignKey("KeyWordsId");

                    b.HasOne("MyRealWorld.DAL.Projects", null)
                        .WithMany("projkw")
                        .HasForeignKey("ProjectsId");
                });

            modelBuilder.Entity("MyRealWorld.DAL.KeyWords", b =>
                {
                    b.Navigation("projkw");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Projects", b =>
                {
                    b.Navigation("projkw");

                    b.Navigation("projpics");
                });
#pragma warning restore 612, 618
        }
    }
}
