// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRealWorld.DAL;

#nullable disable

namespace MyRealWorld.Migrations
{
    [DbContext(typeof(MRWContext))]
    [Migration("20250528171439_FK_projetcs")]
    partial class FK_projetcs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyRealWorld.DAL.KeyWords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Default")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KWS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KeyWords");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Pictures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Project_Pictures", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("PictureID")
                        .HasColumnType("int");

                    b.Property<int>("picturesId")
                        .HasColumnType("int");

                    b.Property<int>("projectsId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "PictureID");

                    b.HasIndex("picturesId");

                    b.HasIndex("projectsId");

                    b.ToTable("Project_Pictures");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MyRealWorld.DAL.ProjectsKW", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("KWId")
                        .HasColumnType("int");

                    b.Property<int>("keyWordsId")
                        .HasColumnType("int");

                    b.Property<int>("projectsId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "KWId");

                    b.HasIndex("keyWordsId");

                    b.HasIndex("projectsId");

                    b.ToTable("ProjectsKW");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Project_Pictures", b =>
                {
                    b.HasOne("MyRealWorld.DAL.Pictures", "pictures")
                        .WithMany("projpics")
                        .HasForeignKey("picturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyRealWorld.DAL.Projects", "projects")
                        .WithMany("projpics")
                        .HasForeignKey("projectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pictures");

                    b.Navigation("projects");
                });

            modelBuilder.Entity("MyRealWorld.DAL.ProjectsKW", b =>
                {
                    b.HasOne("MyRealWorld.DAL.KeyWords", "keyWords")
                        .WithMany("projkw")
                        .HasForeignKey("keyWordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyRealWorld.DAL.Projects", "projects")
                        .WithMany("projkw")
                        .HasForeignKey("projectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("keyWords");

                    b.Navigation("projects");
                });

            modelBuilder.Entity("MyRealWorld.DAL.KeyWords", b =>
                {
                    b.Navigation("projkw");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Pictures", b =>
                {
                    b.Navigation("projpics");
                });

            modelBuilder.Entity("MyRealWorld.DAL.Projects", b =>
                {
                    b.Navigation("projkw");

                    b.Navigation("projpics");
                });
#pragma warning restore 612, 618
        }
    }
}
